### ISSUE TITLE
[FEATURE REQUEST] Add a matrix bridge feature

### ISSUE THREAD

**Issue by ghost** [TeamHarTex/HarTex#11]
Hi, I'd like to know if it is possible to implement a matrix bridge, to be able to transmit events from discord to element and vice versa.

**Comment by HTGAzureX1212** [comment]
This feature is not currently planned in our roadmap; nor does it fit into the main usage of HarTex. Thank you for your suggestion though, but I would not expect this any time soon, at least for now.

**Comment by HTGAzureX1212** [comment]
It turns out that it might be against the ToS to bridge Matrix to Discord with events like Message Create. While bridging Discord *to* Matrix is fine, but:

> the problem is that bridging matrix to discord requires sending messages in discord using systems that are against the TOS

Issue closed with this concern.
