### ISSUE TITLE
Tracking Issue for `twilight-gateway` Migration

### ISSUE THREAD

**Issue by HTGAzureX1212** [TeamHarTex/HarTex#173]
As of https://github.com/twilight-rs/twilight/pull/1809, the `twilight-gateway` crate is completely revamped.

This issue is for raising awareness of this and track progress over rewriting the gateway process to conform to the revamped `twilight-gateway`.

**Comment by HTGAzureX1212** [comment]
This is currently blocked on `ShardEventStream` not implementing the `Send` trait.

**Comment by HTGAzureX1212** [comment]
Part I: https://github.com/TeamHarTex/HarTex/pull/208

**Comment by HTGAzureX1212** [comment]
Part II: #209

**Comment by HTGAzureX1212** [comment]
A current bug of a shard receiving `INVALID_SESSION` upon connecting to the gateway will be fixed by https://github.com/twilight-rs/twilight/pull/1932 on `twilight-rs/twilight`. Temporarily bringing in the branch of the PR (which is synced to `next`) for now until that PR is merged: #258

**Comment by Kayxue** [comment]
🤔

**Comment by HTGAzureX1212** [comment]
Part III: #264

**Comment by HTGAzureX1212** [comment]
Implementation of storing sessions on Ctrl-C is still blocked right now.

**Comment by HTGAzureX1212** [comment]
Closing as already completed most of the things.
