### ISSUE TITLE
Cannot go back to the previous page if it's in the DocumentPage.

### ISSUE THREAD

**Issue by Lunari8546** [TeamHarTex/HarTex#210]
### Reason
Most likely it's because of redirect. Not a groundbreaking bug, but it's annoying.

**Comment by HTGAzureX1212** [comment]
So you mean going back to the previously viewed documentation page is not possible?

As far as I can tell that is an implementation limitation that I did not handle going back to previously viewed pages. 🤔 

Can be a good candidate as something to be implemented later.

**Comment by HTGAzureX1212** [comment]
After investigating further, this is due to the fact that the docs button in the navigation bar leads to `/documentation` which redirects to `/documentation/welcome`.

A temporary solution is to remove the redirection and point the docs button to `/documentation/welcome` directly instead.
