### ISSUE TITLE
Tracking Issue: Support Zed Configuration in `./x.py` setup

### ISSUE THREAD

**Issue by HTGAzureX1212** [TeamHarTex/HarTex#2134]
### Steps:
- [x] create template Zed configuration file https://github.com/TeamHarTex/HarTex/pull/2135
- [ ] create Zed configuration step and register it with builder

**Comment by christolis** [comment]
Can I work on this?

**Comment by HTGAzureX1212** [comment]
For the second step, refer to `tools/bootstrap/src/steps/setup.rs` for how the VSCode and Fleet configurations are implemented.
After implementing a step for setting up Zed, register the step in `steps` method in the `BuildKind` enum, which can be found in `tools/bootstrap/src/builder.rs`.
