### ISSUE TITLE
parse_duration bugs

### ISSUE THREAD

**Issue by Splingush** [TeamHarTex/HarTex#23]
Hello! 
There seem to be some bugs in your parse_duration-function. I hope it is fine if I quickly list them here, instead of opening a pull-request:

- Parsing durations including the digit '9' will fail [1], due to the range being non-inclusive. One might use `..=`
- Seconds are parsed as minutes, due to the `*60`-multiplication [2]
- This function is used with user-input, so it will crash on a typo [3]. Would returning a Result be more applicable here?

[1] <https://github.com/HT-Studios/HarTex-rust-discord-bot/blob/infdev/src/utilities/duration/mod.rs#L29>
[2] <https://github.com/HT-Studios/HarTex-rust-discord-bot/blob/infdev/src/utilities/duration/mod.rs#L46>
[3] <https://github.com/HT-Studios/HarTex-rust-discord-bot/blob/infdev/src/utilities/duration/mod.rs#L49>

Cheers!

**Comment by HTGAzureX1212** [comment]
Greetings, thank you for your thorough report! It is indeed a bug and has been confirmed to be reproducible. A fix will be deployed as soon as possible. Thank you again for your bug report! 👍

**Comment by HTGAzureX1212** [comment]
A "temporary" bug fix is now deployed. Whilst there will still be a follow-up Pull Request to the code with the use of `Result<T, E>`. Thanks @Splingush!
