### ISSUE TITLE
Tracking Issue: `localization` Feature

### ISSUE THREAD

**Issue by HTGAzureX1212** [TeamHarTex/HarTex#52]
This is the tracking issue for the `localization` nightly feature, which implements localization facilities (languages, timezones, etc.)

Currently implemented locales:
- `en_AU` (full translations, cc @Mrcomputer1)
- `en_GB` (full translations, cc @HTG-YT)
- `en_US` (full translations, cc @HTG-YT)
- `zh_HK` (full translations, cc @Lunari8546)
- `zh_TW` (no translations yet)

Planned locales:

**Comment by Lunari8546** [comment]
See Update zh_HK Locale Language Configuration File (hk_2) #53

**Comment by HTGAzureX1212** [comment]
#54 - Australian English `en_AU` is now implemented

**Comment by HTGAzureX1212** [comment]
Refresh of issues. Closing.
