### ISSUE TITLE
RFC #2: Split Bot into Several Processes

### ISSUE THREAD

**Issue by HTGAzureX1212** [TeamHarTex/HarTex#80]
### Feature Name (A Unique Identifier)

process_split

### Starting Date

28 January 2022

### Summary

This RFC proposes to split the bot into separate REST, cache and gateway processes.

### Motivation

This is to provide seamless updates for the bot as the REST, cache and gateway would then not be affected by a restart at all.

### Guide-level Explanation

With this implemented, the bot may have seamless updates as only the bot binary needs to be recompiled and restarted - the REST, cache and gateway processes are intact, and incoming events are to be queued; resuming firing those events after the bot is up again.

### Reference-level Explanation

This RFC comes with a major structural modification.

Processes will communicate with each other using HTTP Requests, with extra security built on top with authorization keys as well as process sandboxing (if possible).

### Drawbacks

- more complication to the code, but it is worth it for a more seamless user experience.

### Rationale & Alternatives

None (for now).

### Unresolved Questions

None (for now).

### Future Possibilities

None (for now).

**Comment by HTGAzureX1212** [comment]
This RFC is now in the **HarTex Team Review** period. Organization members are going to review this RFC.

- [x] @Kayxue 
- [x] @Lunari8546 
- [x] @Mrcomputer1

**Comment by HTG-YT** [comment]
While the RFC does bring along another major code revamp, this does bring more comfort and better user experience in the long run.

The RFC is promising and I think that this has more benefits over drawbacks.

**Comment by Lunari8546** [comment]
In my opinion, as long as it provides better User-experience, I'm totally fine with it even with drawbacks.

**Comment by Mrcomputer1** [comment]
This is a good idea. Although, I don't entirely understand the point of having the REST process, unless the REST process does more than proxying requests to Discord.

**Comment by HTGAzureX1212** [comment]
> This is a good idea. Although, I don't entirely understand the point of having the REST process, unless the REST process does more than proxying requests to Discord.

I should have explained more on the Reference-level Explanation - as this is to prevent currently queued requests to be lost before executing due to bot restarts, and possibly better ratelimiting handling.

**Comment by HTGAzureX1212** [comment]
This RFC is now in the **Final Comment Period**.

The team will now decide on whether or not to accept this RFC.

- [x] @Kayxue - Yes
- [x] @Lunari8546 
- [x] @Mrcomputer1 - Yes

**Comment by Kayxue** [comment]
👍

**Comment by HTGAzureX1212** [comment]
The **Final Comment Period** ended with the decision to **merge**.

The RFC will be implemented.
